name: schedule_app
description: A schedule management app with tasks and classes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
     # Notifikasi Lokal
  flutter_local_notifications: ^17.2.3
  
  # Timezone untuk penjadwalan
  timezone: ^0.9.4
  
  # Permission handler untuk Android 13+
  permission_handler: ^11.3.1
  
  
  # State Management & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  
  # Internationalization
  intl: ^0.18.1
  
  # UI Components
  table_calendar: ^3.0.9
  flutter_colorpicker: ^1.0.3
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "assets/icon/app_icon.png"
